;;;; Test optional loading and real Lisp callbacks against the Python oracle.
(setf sb-impl::*default-external-format* :utf-8)
(defparameter *root* (merge-pathnames "../" (make-pathname :name nil :type nil :defaults *load-truename*)))
(sb-alien:load-shared-object
 (or (sb-ext:posix-getenv "SBEMACS_TEST_LIB")
     (sb-ext:native-namestring (merge-pathnames #+darwin "libsbemacs-term.dylib" #+win32 "libsbemacs-term.dll" #-(or darwin win32) "libsbemacs-term.so" *root*)))
 :dont-save t)
(dolist (file '("package" "ffi" "loader" "core"))
  (load (merge-pathnames (format nil "lisp/~A.lisp" file) *root*)))
(setf sbemacs::*script-directory* (truename (merge-pathnames "lisp/" *root*)))
(let ((sbemacs::*release-build* t))
  (multiple-value-bind (loaded errors)
      (sbemacs::load-scripts :files (sbemacs::script-files sbemacs::*script-directory*)
                             :cache-directory (merge-pathnames "build/test-scripts/" *root*))
    (declare (ignore loaded)) (when errors (error "Script failures: ~S" errors))))
(in-package #:sbemacs)
(defvar *mode-check-count* 0)
(defun mode-check (condition description)
  (incf *mode-check-count*)
  (unless condition (error "Python mode check failed: ~A" description)))
(mode-check (eq (language-highlighter (find "Python" *languages* :key #'language-name :test #'equal)) #'python-mode-highlight)
            "new Python highlighter is the startup default")
(mode-check (equal *active-editing-modes* '("python")) "Python mode starts active")
(mode-check (not (find "python.lisp" (script-files *script-directory*) :key #'file-namestring :test #'equal))
            "legacy Python is excluded from startup scan")
(let* ((stale (pathname (sb-ext:posix-getenv "SBEMACS_MODE_STALE_INSTALL")))
       (old (pathname (sb-ext:posix-getenv "SBEMACS_MODE_OLD_INSTALL")))
       (files (script-files stale)))
  (mode-check (equal (mapcar #'file-namestring files) '("example.lisp"))
              "upgraded install excludes stale Python while keeping other language scripts")
  (mode-check (equal (mapcar #'file-namestring (script-files old)) '("python.lisp"))
              "legacy-only installs still discover their Python script")
  (multiple-value-bind (loaded errors)
      (load-scripts :files files :cache-directory (merge-pathnames "cache/" stale))
    (declare (ignore loaded))
    (mode-check (null errors) "startup cannot execute stale Python on upgrade"))
  (mode-check (eq (language-highlighter (find "Python" *languages* :key #'language-name :test #'equal)) #'python-mode-highlight)
              "cached modern callbacks survive upgrade scan"))
(mode-check (every (lambda (name) (gethash name *commands*)) '("load-mode" "reload-mode" "python-mode" "python-next-definition" "python-previous-definition")) "M-x commands registered")
(mode-check (= (editing-mode-prompt-column "" 80) 11) "initial cursor after prompt")
(mode-check (= (editing-mode-prompt-column "python-mode" 80) 22) "cursor follows typed/completed name")
(mode-check (= (editing-mode-prompt-column "python-mode" 15) 14) "prompt cursor stays within narrow screen")
;; Check paint/position/refresh ordering through screen API adapters.
(let* ((symbols '(message update-display %mode-prompt-display %mode-prompt-move %mode-prompt-refresh screen-rows screen-columns))
       (originals (mapcar #'symbol-function symbols)) (calls nil))
  (unwind-protect
      (progn
        (setf (symbol-function 'message) (lambda (&rest args) (declare (ignore args)) (push :message calls))
              (symbol-function 'update-display) (lambda () (push :redraw calls))
              (symbol-function '%mode-prompt-display) (lambda (prompt response) (push (list :prompt prompt response) calls))
              (symbol-function '%mode-prompt-move) (lambda (row column) (push (list :cursor row column) calls))
              (symbol-function '%mode-prompt-refresh) (lambda () (push :refresh calls))
              (symbol-function 'screen-rows) (lambda () 24)
              (symbol-function 'screen-columns) (lambda () 80))
        (display-editing-mode-prompt "py" "matches")
        (mode-check (equal (nreverse calls) '(:message :redraw (:prompt "Load mode: " "py  [matches]") (:cursor 23 13) :refresh))
                    "cursor placed after input following redraw and before refresh"))
    (loop for symbol in symbols for original in originals do (setf (symbol-function symbol) original))))
(mode-check (member "python-mode" (available-editing-mode-names) :test #'equal) "completion discovers Python mode")
(mode-check (not (member "load-mode" (available-editing-mode-names) :test #'equal)) "loader excluded from mode candidates")
(mode-check (equal (multiple-value-list (complete-editing-mode-name "py" '("python-mode")))
                   '("python-mode" ("python-mode"))) "unique TAB completion")
(mode-check (equal (multiple-value-list (complete-editing-mode-name "PY" '("python-mode")))
                   '("python-mode" ("python-mode"))) "case-insensitive completion")
(mode-check (equal (multiple-value-list (complete-editing-mode-name "py" '("python-mode" "python-tools-mode")))
                   '("python-" ("python-mode" "python-tools-mode"))) "ambiguous common prefix")
(mode-check (equal (multiple-value-list (complete-editing-mode-name "missing" '("python-mode")))
                   '("missing" nil)) "unmatched completion keeps input")
;; Exercise the prompt state machine without running any editing commands.
(let ((old-key (symbol-function 'get-key)) (old-name (symbol-function 'get-key-name))
      (old-message (symbol-function 'message)) (old-display (symbol-function 'update-display))
      (old-prompt (symbol-function 'display-editing-mode-prompt)))
  (unwind-protect
      (progn
        (setf (symbol-function 'display-editing-mode-prompt) (lambda (typed status) (declare (ignore typed status)) nil)
              (symbol-function 'message) (lambda (&rest args) (declare (ignore args)) t)
              (symbol-function 'update-display) (lambda () nil)
              (symbol-function 'get-key-name) (lambda () ""))
        (dolist (case (list (list (list "p" "y" (string #\Tab) (string #\Return)) "python-mode")
                           (list (list "p" "x" (string (code-char 127)) "y" (string #\Tab) (string #\Return)) "python-mode")
                           (list (list "p" (string (code-char 21)) "p" "y" (string #\Tab) (string #\Return)) "python-mode")
                           (list (list "p" (string (code-char 7))) nil)))
          (let ((keys (first case)))
            (setf (symbol-function 'get-key) (lambda () (or (pop keys) (error "Prompt read beyond fixture"))))
            (mode-check (equal (read-editing-mode-name) (second case)) "TAB/backspace/clear/cancel prompt")))
        (let ((*editing-modes* (make-hash-table :test 'equal)))
          (setf (gethash "python" *editing-modes*) t (gethash "python-tools" *editing-modes*) t)
          (loop for tabs from 2 to 4 for expected in '("python-mode" "python-tools-mode" "python-mode") do
            (let ((keys (append (list "p" "y") (make-list tabs :initial-element (string #\Tab))
                                (list (string #\Return)))))
              (setf (symbol-function 'get-key) (lambda () (or (pop keys) (error "Prompt read beyond cycle fixture"))))
              (mode-check (equal (read-editing-mode-name) expected) "repeated TAB cycles and wraps ambiguous candidates")))))
    (setf (symbol-function 'get-key) old-key (symbol-function 'get-key-name) old-name
          (symbol-function 'message) old-message (symbol-function 'update-display) old-display
          (symbol-function 'display-editing-mode-prompt) old-prompt)))
(mode-check (equal (activate-editing-mode "python-mode") "python") "activation by mode name")
(mode-check (eq (language-highlighter (find "Python" *languages* :key #'language-name :test #'equal)) #'python-mode-highlight) "real callback installed")
(mode-check (eq (indent-spec-style (gethash "Python" *indentation*)) :python-smart) "indent style installed")
(mode-check (equal (indentation-for-text "Python" (format nil "if x:~%")) 4) "engine indentation entry point")
(dolist (name '("../python" "/tmp/python" "" "no-such-mode"))
  (mode-check (handler-case (progn (activate-editing-mode name) nil) (error () t)) "invalid/unknown names rejected"))
(let ((*script-directory* nil) (*editing-mode-directory* nil))
  (mode-check (equal (activate-editing-mode "python") "python") "bundled definitions work without source directory"))
(let ((*default-pathname-defaults* #p"/private/tmp/") (*script-directory* nil))
  (mode-check (equal (editing-mode-path "python")
                     (truename (merge-pathnames "lisp/modes/python-mode.lisp" cl-user::*root*)))
              "mode lookup anchored beside loader from unrelated directory")
  (let ((original (symbol-function 'load-script)) (seen nil))
    (unwind-protect
        (progn
          (setf (symbol-function 'load-script)
                (lambda (path &optional cache)
                  (declare (ignore cache))
                  (setf seen *default-pathname-defaults*)
                  (funcall original path)))
          (activate-editing-mode "python")
          (mode-check (equal seen *editing-mode-directory*) "relative mode loads use modes directory")
          (mode-check (equal *default-pathname-defaults* #p"/private/tmp/") "caller directory restored after loading"))
      (setf (symbol-function 'load-script) original))))
(activate-editing-mode "python")
(mode-check (= 1 (count "python" *active-editing-modes* :test #'equal)) "activation idempotent")
(mode-check (= 1 (count "python" *mode-menu-providers* :key #'car :test #'equal)) "menu contribution idempotent")
(let ((source (format nil "变量 = 1~%text = \"\"\"~%def fake():~%\"\"\"~%async def real():~%    pass~%class Other:~%    pass~%")))
  (mode-check (equal (python-mode-definition-positions source)
                     (mapcar (lambda (needle) (length (octets (subseq source 0 (search needle source)))))
                             '("async def real" "class Other"))) "definition navigation byte positions"))
;; Test provider against window API adapters; preserve original editor functions.
(let ((old-window (symbol-function 'call-in-window-of)) (old-filename (symbol-function 'buffer-filename))
      (old-count (symbol-function 'window-count))
      (filename "example.py") (buttons '(("HELP" "C-h") ("SAVE" "C-x C-s") ("UNDO" "C-/"))))
  (unwind-protect
      (progn
        (setf (symbol-function 'call-in-window-of) (lambda (name fn) (declare (ignore name)) (funcall fn))
              (symbol-function 'buffer-filename) (lambda () filename)
              (symbol-function 'window-count) (lambda () 1))
        (mode-check (= (length (python-mode-menu "example" buttons)) 3) "Python editing menu")
        (mode-check (equal (mapcar #'first (subseq (python-mode-menu "example" *mode-line-menu*) 0 3))
                           '("?" "#" "SAVE")) "Python tools preserve leading Help/Quit/More controls")
        (mode-check (let ((*menu-full* t)) (search "Previous definition" (more-menu-text (python-mode-menu "example" *full-menu*))))
                    "More lists language-specific actions")
        (let ((*menu-region* t))
          (mode-check (equal (mapcar #'first (python-mode-menu "example" (mode-line-buttons "example")))
                             '("?" "#" "SAVE" "UNDO" "COPY" "DELETE" "INDENT" "MORE" "QUIT"))
                      "Python selection actions"))
        (setf filename "example.lisp")
        (mode-check (equal (python-mode-menu "example" buttons) buttons) "other file menus preserved"))
    (setf (symbol-function 'call-in-window-of) old-window (symbol-function 'buffer-filename) old-filename
          (symbol-function 'window-count) old-count)))
(mode-check (equal (python-mode-menu "example.py" '(("HELP" "C-h"))) '(("HELP" "C-h")))
            "menu preserves buttons without an initialized editor window")
(let* ((path (or (sb-ext:posix-getenv "SBEMACS_PYTHON_ORACLE") (error "Run lisp/py2sexpr/test_lisp_python_mode.py")))
       (fixtures (let ((*read-eval* nil)) (with-open-file (in path :external-format :utf-8) (read in)))))
  (loop for fixture in fixtures for index from 1 do
    (destructuring-bind (kind source expected-or-line &optional expected-indent) fixture
      (ecase kind
        (:colors
         (let* ((raw (octets source)) (colors (make-array (length raw) :element-type '(unsigned-byte 8) :initial-element 0)))
           (python-mode-highlight nil raw (length raw) colors)
           (mode-check (equalp colors (coerce expected-or-line 'vector)) (format nil "color oracle ~D" index))
           ;; Invoke the actual foreign-callable entry point with pinned buffers.
           (fill colors 0)
           (sb-sys:with-pinned-objects (raw colors)
             (sb-alien:alien-funcall (sb-alien:alien-callable-function 'lisp-highlight)
                                   "example.py" "example" (sb-sys:vector-sap raw)
                                   (length raw) (sb-sys:vector-sap colors)))
           (mode-check (equalp colors (coerce expected-or-line 'vector)) (format nil "C callback oracle ~D" index))))
        (:indent
         (let* ((raw (octets (concatenate 'string source expected-or-line)))
                (context (make-indent-context :text raw :line (length (octets source)) :spec (gethash "Python" *indentation*))))
           (mode-check (eql (python-mode-indentation context) expected-indent) (format nil "indent oracle ~D" index))))))))
(format t "~&~D optional loader and Lisp/Python oracle checks passed.~%" *mode-check-count*)
