;;;; Nim editing mode for SBEmacs. Uses the standard mode/indent/menu APIs.
;;;; The pm-* position/token helpers are supplied by SBEmacs's bundled Python mode.
(in-package #:sbemacs)
(declaim (optimize (safety 3) (debug 2)))
(defparameter *nim-keywords*
  '("addr" "and" "as" "asm" "bind" "block" "break" "case" "cast" "concept"
    "const" "continue" "converter" "defer" "discard" "distinct" "div" "do"
    "elif" "else" "end" "enum" "except" "export" "finally" "for" "from"
    "func" "if" "import" "in" "include" "interface" "is" "isnot" "iterator"
    "let" "macro" "method" "mixin" "mod" "nil" "not" "notin" "object"
    "of" "or" "out" "proc" "ptr" "raise" "ref" "return" "shl" "shr"
    "static" "template" "try" "tuple" "type" "using" "var" "when" "while"
    "xor" "yield"))
(defparameter *nim-definers* '("proc" "func" "method" "iterator" "converter" "macro" "template"))
(declaim (ftype (function (string) string) nim-normalize)
         (ftype (function (string) list) nim-lex))
(defun nim-normalize (word)
  ;; Nim preserves the case of the first letter; later letters ignore case/underscores.
  (if (zerop (length word)) word
      (concatenate 'string (subseq word 0 1) (string-downcase (remove #\_ (subseq word 1))))))
(defun nim-lex (source)
  "Tolerant lexer: nested comments, raw/triple strings, backtick names and numeric suffixes."
  (let ((i 0) (n (length source)) (tokens nil))
    (labels ((emit (kind start &optional (closed t) (quote ""))
               (push (make-pm-token :kind kind :start start :end i :value (subseq source start i)
                                    :closed closed :quote quote) tokens))
             (at (text) (pm-at source text i)))
      (loop while (< i n) for start = i for c = (char source i) do
        (cond
          ((find c '(#\Space #\Tab #\Return)) (incf i))
          ((char= c #\Newline) (incf i) (emit :newline start))
          ((or (at "#[") (at "##["))
           (let ((stack (list (if (at "##[") "]##" "]#"))))
             (incf i (if (at "##[") 3 2))
             (loop while (and (< i n) stack) do
               (cond ((at "##[") (push "]##" stack) (incf i 3))
                     ((at "#[") (push "]#" stack) (incf i 2))
                     ((at (car stack)) (incf i (length (pop stack))))
                     (t (incf i))))
             (emit :comment start (null stack))))
          ((char= c #\#) (setf i (or (position #\Newline source :start i) n)) (emit :comment start))
          ((char= c #\`) (incf i)
           (setf i (if (position #\` source :start i) (1+ (position #\` source :start i)) n))
           (emit :name start))
          ((digit-char-p c)
           (incf i)
           (loop while (and (< i n)
                            (or (alphanumericp (char source i)) (find (char source i) "_'" )
                                (and (char= (char source i) #\.) (not (pm-at source ".." i)))
                                (and (find (char source i) "+-") (> i start)
                                     (find (char source (1- i)) "eE")))) do (incf i))
           (emit :number start))
          (t
           (let ((opening i) (raw nil))
             (when (pm-name-start c)
               (incf i) (loop while (and (< i n) (pm-name-part (char source i))) do (incf i))
               (if (and (< i n) (char= (char source i) #\"))
                   (setf opening i raw t) (setf opening nil)))
             (cond ((null opening) (emit :name start))
                   ((find (char source opening) "\"'")
                    (let* ((q (char source opening))
                           (delimiter (if (and (char= q #\") (pm-at source "\"\"\"" opening)) "\"\"\"" (string q)))
                           (closed nil))
                      (setf i (+ opening (length delimiter)))
                      (loop while (< i n) do
                        (cond ((and raw (= (length delimiter) 1) (pm-at source "\"\"" i)) (incf i 2))
                              ((pm-at source delimiter i) (incf i (length delimiter)) (setf closed t) (return))
                              ((and (not raw) (= (length delimiter) 1) (char= (char source i) #\\)) (setf i (min n (+ i 2))))
                              ((and (= (length delimiter) 1) (char= (char source i) #\Newline)) (return))
                              (t (incf i))))
                      (emit :string start closed delimiter)))
                   (t (incf i) (emit :operator start)))))))
      (nreverse tokens))))
(declaim (ftype function nim-lisp-highlight nim-lisp-indentation nim-highlight nim-indentation nim-levels nim-menu nim-navigate nim-command-line))
(defun nim-lisp-highlight (language text length colors)
  (declare (ignore language))
  (let* ((source (octets-string text 0 length)) (offsets (pm-offsets source)) (expect nil))
    (fill colors (color-id :alpha) :end length)
    (dolist (token (nim-lex source))
      (let* ((word (nim-normalize (pm-token-value token)))
             (face (case (pm-token-kind token)
                     (:comment :comment) (:string :string) (:number :digits) (:operator :symbol)
                     (:name (cond (expect (setf expect nil) :heading)
                                  ((member word *nim-keywords* :test #'equal)
                                   (setf expect (member word *nim-definers* :test #'equal)) :keyword)
                                  ((member word '("true" "false") :test #'equal) :keyword)
                                  (t :alpha)))
                     (otherwise :alpha))))
        (when (eq (pm-token-kind token) :newline) (setf expect nil))
        (pm-paint (pm-token-start token) (pm-token-end token) face offsets colors))))
  colors)
(defun nim-lisp-indentation (context)
  (let* ((raw (ictx-text context)) (source (octets-string raw 0 (length raw)))
         (pos (length (octets-string raw 0 (ictx-line context))))
         (before (subseq source 0 pos)) (width (ictx-width context))
         (tokens (nim-lex before)) (current (nim-lex (subseq source pos))))
    (when (and tokens (not (pm-token-closed (car (last tokens)))))
      (return-from nim-lisp-indentation nil))
    (multiple-value-bind (statements pending brackets) (pm-statements tokens)
      (when brackets
        (let ((opener (first brackets)))
          (return-from nim-lisp-indentation
            (if (and current (equal (pm-token-value (first current)) (pm-closing (pm-token-value opener))))
                (pm-indentation before (pm-token-start opener))
                (+ (pm-indentation before (pm-token-start opener)) width)))))
      (when pending (setf statements (append statements (list pending))))
      (unless statements (return-from nim-lisp-indentation 0))
      (let* ((previous (car (last statements))) (head (pm-token-value (first previous)))
             (tail (pm-token-value (car (last previous))))
             (base (pm-indentation before (pm-token-start (first previous))))
             (first (and current (pm-token-value (first current))))
             (partners (cdr (assoc first '(("elif" "if" "when" "elif")
                                          ("else" "if" "when" "elif" "case" "of" "for" "while" "try" "except")
                                          ("of" "case" "of") ("except" "try" "except")
                                          ("finally" "try" "except")) :test #'equal))))
        (when partners
          (let ((limit (+ base width)))
            (dolist (statement (reverse statements))
              (let ((level (pm-indentation before (pm-token-start (first statement))))
                    (word (pm-token-value (first statement))))
                (when (and (<= level limit) (member word partners :test #'equal))
                  (return-from nim-lisp-indentation (if (equal word "case") (+ level width) level)))
                (setf limit (min level limit))))))
        (cond ((or (member tail '(":" "=") :test #'equal)
                   (member head '("case" "type" "var" "let" "const") :test #'equal)
                   (member tail '("object" "enum" "tuple") :test #'equal))
               ;; A declaration with an initializer is not a section header.
               (if (and (member head '("let" "var" "const" "type") :test #'equal)
                        (not (member tail '("=" "object" "enum" "tuple") :test #'equal)) (second previous)) base (+ base width)))
              ((member tail '("+" "-" "*" "/" "," "and" "or" "&") :test #'equal) (+ base width))
              (t base))))))
(defun nim-levels (context)
  (let ((col (nim-indentation context)) (width (ictx-width context)))
    (when col (sort (remove-duplicates (cons col (loop for n from 0 to (+ col width) by width collect n))) #'<))))
(defun nim-file-p (name)
  (and name (member (string-downcase (or (pathname-type name) "")) '("nim" "nims" "nimble") :test #'equal)))
(defun nim-navigate (direction)
  (let* ((source (buffer-substring 0 (buffer-size))) (offsets (pm-offsets source))
         (positions (loop for token in (nim-lex source)
                          when (and (eq (pm-token-kind token) :name)
                                    (member (pm-token-value token) *nim-definers* :test #'equal))
                          collect (aref offsets (pm-token-start token))))
         (here (point)) (target (if (plusp direction) (find-if (lambda (n) (> n here)) positions)
                                   (find-if (lambda (n) (< n here)) (reverse positions)))))
    (if target (goto-char target) (message "No further Nim definition"))))
(defcommand nim-next-definition () (nim-navigate 1))
(defcommand nim-previous-definition () (nim-navigate -1))
(defun nim-shell-quote (text)
  #+win32 (progn (when (find-if (lambda (c) (or (find c "\"%") (find c (list #\Return #\Newline)))) text) (error "Unsupported character in Nim path"))
                 (format nil "\"~A\"" text))
  #-win32 (with-output-to-string (out)
            (write-char #\' out)
            (loop for c across text do (if (char= c #\') (write-string "'\"'\"'" out) (write-char c out)))
            (write-char #\' out)))
(defun nim-command-line (file run arguments)
  (format nil "nim c ~A--hints:off ~A~A"
          (if run "-r " "") (nim-shell-quote file)
          (if (and run (plusp (length arguments))) (concatenate 'string " " arguments) "")))
(defun nim-execute (run)
  (handler-case
      (let ((file (buffer-filename)))
        (unless (and file (equal (string-downcase (or (pathname-type file) "")) "nim"))
          (return-from nim-execute (message "Open and save a .nim source file first.")))
        (unless (save-buffer (get-buffer-name))
          (return-from nim-execute (message "Save failed; compilation cancelled.")))
        (when (buffer-modified-p) (return-from nim-execute (message "Save failed; compilation cancelled.")))
        (let* ((arguments (if run (prompt "Nim program arguments: " "") ""))
               (command (nim-command-line (file-namestring file) run arguments)))
          (shell-command-window) (insert command) (shell-command-run)))
    (error (e) (message "Nim: ~A" e))))
(defcommand nim-build () (nim-execute nil))
(defcommand nim-run () (nim-execute t))
(defun nim-menu (buffer buttons)
  (if (if *menu-rendering* (nim-file-p *menu-filename*)
          (and (plusp (window-count)) (call-in-window-of buffer (lambda () (nim-file-p (buffer-filename))))))
      (if *menu-full*
          (append (remove "QUIT" buttons :key #'first :test #'equal)
                  '(("#" "M-;") ("BUILD" nim-build) ("RUN" nim-run)
                    ("DEF>" nim-next-definition) ("<DEF" nim-previous-definition) ("QUIT" "C-x C-c")))
          (loop for button in buttons append
                (if (equal (first button) "?") (list button '("#" "M-;")) (list button))))
      buttons))
;;; Optional compiled Nim implementation. The C renderer already reaches this
;;; highlighter through highlight-buffer-text; the indentation command uses the
;;; same byte-oriented ABI. The Lisp implementation remains the fallback.
(defvar *nim-native-library* nil)
(defparameter *nim-native-enabled* t)
(sb-alien:define-alien-routine ("sbemacs_nim_abi" %nim-native-abi) sb-alien:int)
(sb-alien:define-alien-routine ("sbemacs_nim_highlight" %nim-native-highlight) sb-alien:int
  (text sb-alien:system-area-pointer) (length (sb-alien:unsigned #.sb-vm:n-word-bits))
  (colors sb-alien:system-area-pointer))
(sb-alien:define-alien-routine ("sbemacs_nim_indent" %nim-native-indent) sb-alien:int
  (text sb-alien:system-area-pointer) (length (sb-alien:unsigned #.sb-vm:n-word-bits))
  (line (sb-alien:unsigned #.sb-vm:n-word-bits)) (width sb-alien:int))
(defun reset-nim-native-library () (setf *nim-native-library* nil))
(pushnew 'reset-nim-native-library sb-ext:*init-hooks*)
(defun ensure-nim-native-library ()
  (when *nim-native-enabled*
    (or *nim-native-library*
        (let* ((name (format nil "libsbemacs-nim-mode.~A" *library-extension*))
               (override (sb-ext:posix-getenv "SBEMACS_NIM_MODE_LIB"))
               (candidates (if (and override (plusp (length override)))
                               (list (pathname override))
                               (remove nil
                                 (list (and *script-directory* (merge-pathnames (concatenate 'string "../" name) *script-directory*))
                                       (and *source-directory* (merge-pathnames name *source-directory*))))))
               (path (find-if #'probe-file candidates)))
          (when path
            (sb-alien:load-shared-object (native (truename path)) :dont-save t)
            (unless (= 1 (%nim-native-abi)) (error "Unsupported Nim mode library ABI"))
            (setf *nim-native-library* (truename path)))))))
(defun nim-highlight (language text length colors)
  (declare (type octets text colors) (type fixnum length))
  (if (ensure-nim-native-library)
      (progn
        (unless (<= 0 length (length text) (length colors))
          (error "Invalid Nim highlighting buffer lengths"))
        (sb-sys:with-pinned-objects (text colors)
          (unless (zerop (%nim-native-highlight (sb-sys:vector-sap text) length (sb-sys:vector-sap colors)))
            (error "Native Nim highlighting failed")))
        colors)
      (nim-lisp-highlight language text length colors)))
(defun nim-indentation (context)
  (if (ensure-nim-native-library)
      (let ((text (ictx-text context)))
        (declare (type octets text))
        (sb-sys:with-pinned-objects (text)
          (let ((result (%nim-native-indent (sb-sys:vector-sap text) (length text)
                                           (ictx-line context) (ictx-width context))))
            (cond ((= result -1) nil) ((minusp result) (error "Native Nim indentation failed"))
                  (t result)))))
      (nim-lisp-indentation context)))
(defcommand nim-native-status ()
  (message "Nim mode: ~A" (or (ensure-nim-native-library) "Lisp fallback (native library absent)")))

(defun install-nim-mode ()
  (define-language "Nim" :extensions '(".nim" ".nims" ".nimble") :line-comment "#" :highlighter #'nim-highlight)
  (setf (gethash :nim-smart *indent-styles*) (cons #'nim-indentation (lambda (text start) (declare (ignore text start)) nil)))
  (define-indentation "Nim" :style :nim-smart :width 2 :tabs nil :cycle t :levels #'nim-levels
                      :electric-keys ":" :electric-words '("elif" "else" "of" "except" "finally"))
  (install-mode-menu "nim" #'nim-menu))
(register-editing-mode "nim" #'install-nim-mode)
(defcommand nim-mode () (load-mode "nim"))
