;;;; Hand-written Common Lisp implementation of languages/python.synpy.
;;;; Startup installs this standard mode; M-x python-mode reloads it. No Python runtime.
(in-package #:sbemacs)
(declaim (optimize (safety 3) (debug 2)))
(defparameter *pm-keywords*
  '("False" "None" "True" "and" "as" "assert" "async" "await" "break" "class"
    "continue" "def" "del" "elif" "else" "except" "finally" "for" "from" "global"
    "if" "import" "in" "is" "lambda" "nonlocal" "not" "or" "pass" "raise"
    "return" "try" "while" "with" "yield"))
(defparameter *pm-builtins*
  '("abs" "all" "any" "ascii" "bin" "bool" "breakpoint" "bytearray" "bytes"
    "callable" "chr" "classmethod" "complex" "dict" "dir" "divmod" "enumerate"
    "eval" "exec" "filter" "float" "format" "frozenset" "getattr" "globals"
    "hasattr" "hash" "help" "hex" "id" "input" "int" "isinstance" "issubclass"
    "iter" "len" "list" "locals" "map" "max" "memoryview" "min" "next" "object"
    "oct" "open" "ord" "pow" "print" "property" "range" "repr" "reversed" "round"
    "set" "setattr" "slice" "sorted" "staticmethod" "str" "sum" "super" "tuple"
    "type" "vars" "zip" "__import__"))
(defparameter *pm-prefixes* '("r" "u" "b" "f" "br" "rb" "fr" "rf" "t" "tr" "rt"))
(defstruct pm-token kind start end value (prefix "") (quote "") (closed t))

(defun pm-name-start (c)
  (or (char= c #\_) (alpha-char-p c)
      (member (sb-unicode:general-category c) '(:lo :nl))))
(defun pm-name-part (c)
  (or (pm-name-start c) (digit-char-p c)
      (member (sb-unicode:general-category c) '(:mn :mc :nd :pc))))
(defun pm-at (source delimiter position)
  (let ((end (+ position (length delimiter))))
    (and (<= end (length source)) (string= delimiter source :start2 position :end2 end))))
(defun pm-string-end (source opening)
  (let* ((q (char source opening)) (triple (make-string 3 :initial-element q))
         (delimiter (if (pm-at source triple opening) triple (string q)))
         (cursor (+ opening (length delimiter))) (n (length source)))
    (loop while (< cursor n) do
      (cond ((char= (char source cursor) #\\) (incf cursor 2))
            ((pm-at source delimiter cursor) (return-from pm-string-end (values (+ cursor (length delimiter)) delimiter t)))
            ((and (= (length delimiter) 1) (find (char source cursor) '(#\Return #\Newline)))
             (return-from pm-string-end (values cursor delimiter nil)))
            (t (incf cursor))))
    (values n delimiter nil)))
(defun pm-number-end (source start)
  (let ((i start) (n (length source)))
    (labels ((in (chars) (and (< i n) (find (char source i) chars)))
             (digits () (loop while (in "0123456789_") do (incf i))))
      (when (and (< (1+ start) n) (char= (char source start) #\0)
                 (find (char-downcase (char source (1+ start))) "xob"))
        (let ((digits (case (char-downcase (char source (1+ start)))
                        (#\x "0123456789abcdefABCDEF_") (#\o "01234567_") (#\b "01_"))))
          (incf i 2) (loop while (in digits) do (incf i))
          (return-from pm-number-end i)))
      (digits)
      (when (in ".") (incf i) (digits))
      (when (in "eE")
        (let ((e (1+ i)))
          (when (and (< e n) (find (char source e) "+-")) (incf e))
          (when (and (< e n) (digit-char-p (char source e)))
            (setf i (1+ e)) (digits))))
      (when (in "jJ") (incf i))
      i)))
(defun pm-lex (source)
  "Tolerant character lexer. Positions are converted to bytes only at callbacks."
  (declare (type string source))
  (let ((i 0) (n (length source)) (tokens nil))
    (labels ((emit (kind start end &optional (prefix "") (quote "") (closed t))
               (push (make-pm-token :kind kind :start start :end end :value (subseq source start end)
                                    :prefix prefix :quote quote :closed closed) tokens)))
      (loop while (< i n) do
        (let* ((start i) (c (char source i)) (opening i) (prefix ""))
          (cond
            ((find c '(#\Space #\Tab #\Return #\Page)) (incf i))
            ((char= c #\Newline) (incf i) (emit :newline start i))
            ((char= c #\#) (setf i (or (position #\Newline source :start i) n)) (emit :comment start i))
            (t
             (when (pm-name-start c)
               (incf i)
               (loop while (and (< i n) (pm-name-part (char source i))) do (incf i))
               (let ((word (subseq source start i)))
                 (if (and (member (string-downcase word) *pm-prefixes* :test #'equal)
                          (< i n) (find (char source i) "\"'"))
                     (setf prefix (string-downcase word) opening i)
                     (setf opening nil))))
             (cond
               ((null opening) (emit :name start i))
               ((find (char source opening) "\"'")
                (multiple-value-bind (end quote closed) (pm-string-end source opening)
                  (setf i end) (emit :string start i prefix quote closed)))
               ((or (find c "0123456789")
                    (and (char= c #\.) (< (1+ i) n) (find (char source (1+ i)) "0123456789")))
                (setf i (pm-number-end source start)) (emit :number start i))
               (t (setf i (1+ start)) (emit :operator start i))))))))
    (nreverse tokens)))
(defun pm-line-start (source pos)
  (let ((p (position #\Newline source :end pos :from-end t))) (if p (1+ p) 0)))
(defun pm-column (source pos)
  (loop with col = 0 for i from (pm-line-start source pos) below pos
        do (setf col (if (char= (char source i) #\Tab) (* 8 (1+ (floor col 8))) (1+ col)))
        finally (return col)))
(defun pm-indentation (source pos)
  (let ((i (pm-line-start source pos)))
    (loop while (and (< i (length source)) (find (char source i) '(#\Space #\Tab))) do (incf i))
    (pm-column source i)))
(defun pm-closing (value)
  (cdr (assoc value '(("(" . ")") ("[" . "]") ("{" . "}")) :test #'equal)))
(defun pm-statements (tokens)
  (let ((statements nil) (current nil) (brackets nil) (in-string nil))
    (dolist (token tokens)
      (let ((value (pm-token-value token)))
        (case (pm-token-kind token)
          (:comment)
          (:newline
           (cond ((and current (not brackets) (not (equal (pm-token-value (car current)) "\\")))
                  (push (nreverse current) statements) (setf current nil))
                 ((and current (equal (pm-token-value (car current)) "\\")) (pop current))))
          (otherwise
           (push token current)
           (cond ((eq (pm-token-kind token) :string)
                  (setf in-string (and (not (pm-token-closed token))
                                       (or (= (length (pm-token-quote token)) 3) (ends-with-p "\\" value)))))
                 ((pm-closing value) (push token brackets))
                 ((and brackets (equal value (pm-closing (pm-token-value (car brackets))))) (pop brackets)))))))
    (values (nreverse statements) (nreverse current) brackets in-string)))
(defun pm-field-end (source start end)
  (let ((i start) (stack nil) (expression-end end))
    (loop while (< i end) for c = (char source i) do
      (cond ((find c "\"'") (setf i (nth-value 0 (pm-string-end source i))))
            ((char= c #\#) (setf i (let ((p (position #\Newline source :start i))) (if p (1+ p) end))))
            (t
             (cond ((find c "([{") (push (string c) stack))
                   ((find c ")]}")
                    (cond ((and stack (equal (string c) (pm-closing (car stack)))) (pop stack))
                          ((and (char= c #\}) (null stack)) (return-from pm-field-end (values (min expression-end i) i)))))
                   ((and (null stack) (or (char= c #\:) (and (char= c #\!) (not (pm-at source "!=" i)))))
                    (setf expression-end (min expression-end i))))
             (incf i))))
    (values expression-end end)))
(defun pm-offsets (source)
  (let ((offsets (make-array (1+ (length source)) :initial-element 0)))
    (loop for c across source for i from 1
          do (setf (aref offsets i) (+ (aref offsets (1- i))
                                      (let ((code (char-code c))) (cond ((< code 128) 1) ((< code 2048) 2) ((< code 65536) 3) (t 4))))))
    offsets))
(defun pm-paint (start end face offsets colors)
  (loop for i from (aref offsets start) below (aref offsets end) do (setf (aref colors i) (color-id face))))
(declaim (ftype function pm-paint-tokens pm-paint-fields))
(defun pm-paint-fields (source start end offsets colors)
  (let ((i start))
    (loop while (< i end) do
      (cond ((or (pm-at source "{{" i) (pm-at source "}}" i)) (incf i 2))
            ((char= (char source i) #\{)
             (multiple-value-bind (expr close) (pm-field-end source (1+ i) end)
               (pm-paint i (1+ i) :symbol offsets colors)
               (pm-paint-tokens source (pm-lex (subseq source (1+ i) expr)) offsets colors (1+ i))
               (when (< expr close)
                 (pm-paint expr (1+ expr) :symbol offsets colors)
                 (pm-paint-fields source (1+ expr) close offsets colors))
               (when (< close end) (pm-paint close (1+ close) :symbol offsets colors))
               (setf i (min (1+ close) end))))
            (t (incf i))))))
(defun pm-paint-tokens (source tokens offsets colors &optional (origin 0))
  (let* ((vector (coerce tokens 'vector)) (n (length vector))
         (next-values (make-array n :initial-element "")) (headers (make-array n :initial-element nil))
         (next "") (line-end "") (expect nil) (decorator nil) (significant nil))
    (loop for i downfrom (1- n) to 0 for token = (aref vector i) do
      (setf (aref next-values i) next)
      (case (pm-token-kind token)
        (:newline (setf next "" line-end ""))
        (:comment)
        (otherwise (setf next (pm-token-value token)) (when (equal line-end "") (setf line-end next))))
      (setf (aref headers i) (equal line-end ":")))
    (loop for token across vector for i from 0
          for start = (+ origin (pm-token-start token)) for end = (+ origin (pm-token-end token))
          for word = (pm-token-value token) for next = (aref next-values i)
          do (let ((face :alpha))
               (case (pm-token-kind token)
                 (:newline (setf decorator nil expect nil significant nil))
                 (:comment (setf face :comment)) (:string (setf face :string)) (:number (setf face :digits))
                 (:operator (setf face :symbol) (when (and (equal word "@") (null significant)) (setf decorator t)))
                 (:name
                  (cond (expect (setf face :heading expect nil))
                        ((member word *pm-keywords* :test #'equal) (setf face :keyword expect (member word '("def" "class") :test #'equal)))
                        ((and (null significant) (member word '("match" "case") :test #'equal) (aref headers i)) (setf face :keyword))
                        ((and (null significant) (equal word "type") (not (member next '("=" "(") :test #'equal))
                              (plusp (length next)) (pm-name-start (char next 0))) (setf face :keyword))
                        (decorator (setf face :link))
                        ((and (member word *pm-builtins* :test #'equal) (equal next "(")
                              (not (and significant (equal (pm-token-value (car significant)) ".")))) (setf face :emphasis)))))
               (pm-paint start end face offsets colors)
               (when (and (eq (pm-token-kind token) :string) (or (find #\f (pm-token-prefix token)) (find #\t (pm-token-prefix token))))
                 (pm-paint-fields source (+ start (length (pm-token-prefix token)) (length (pm-token-quote token)))
                                  (if (pm-token-closed token) (- end (length (pm-token-quote token))) end) offsets colors))
               (unless (member (pm-token-kind token) '(:comment :newline)) (push token significant))))))
(defun python-mode-highlight (language text length colors)
  (declare (ignore language) (type fixnum length))
  (let* ((source (octets-string text 0 length)) (offsets (pm-offsets source)))
    (fill colors (color-id :alpha) :end length)
    (pm-paint-tokens source (pm-lex source) offsets colors)
    colors))
(defun python-mode-indentation (context)
  (let* ((raw (ictx-text context)) (source (octets-string raw 0 (length raw)))
         (pos (length (octets-string raw 0 (ictx-line context))))
         (before (subseq source 0 pos))
         (current-line (string-left-trim '(#\Space #\Tab) (subseq source pos (or (position #\Newline source :start pos) (length source)))))
         (width (ictx-width context)))
    (multiple-value-bind (statements pending brackets in-string) (pm-statements (pm-lex before))
      (when in-string (return-from python-mode-indentation nil))
      (when brackets
        (let* ((opener (car brackets)) (start (pm-token-start opener)) (end (pm-token-end opener))
               (content (subseq before end (or (position #\Newline before :start end) (length before))))
               (trim (string-left-trim '(#\Space #\Tab #\Return) content)))
          (return-from python-mode-indentation
            (cond ((and (plusp (length current-line)) (equal (subseq current-line 0 1) (pm-closing (pm-token-value opener))))
                   (pm-indentation before start))
                  ((and (plusp (length trim)) (not (char= (char trim 0) #\#)))
                   (pm-column before (+ end (- (length content) (length (string-left-trim '(#\Space #\Tab) content))))))
                  (t (+ (pm-indentation before start) width))))))
      (when pending (return-from python-mode-indentation (+ (pm-indentation before (pm-token-start (first pending))) width)))
      (unless statements (return-from python-mode-indentation 0))
      (let* ((previous (car (last statements))) (base (pm-indentation before (pm-token-start (first previous))))
             (tokens (pm-lex current-line))
             (first (if (and tokens (eq (pm-token-kind (first tokens)) :name)) (pm-token-value (first tokens)) ""))
             (partners (cdr (assoc first '(("elif" "if" "elif") ("else" "if" "elif" "for" "while" "try" "except")
                                          ("except" "try" "except") ("finally" "try" "except" "else") ("case" "match" "case")) :test #'equal))))
        (when (and (second tokens) (member (pm-token-value (second tokens)) '("=" "(" ".") :test #'equal)) (setf partners nil))
        (when partners
          (let ((limit (if (equal (pm-token-value (car (last previous))) ":") (+ base width) base)))
            (dolist (statement (reverse statements))
              (let ((level (pm-indentation before (pm-token-start (first statement))))
                    (head (pm-token-value (first statement))))
                (when (and (equal head "async") (second statement)) (setf head (pm-token-value (second statement))))
                (when (and (<= level limit) (member head partners :test #'equal) (equal (pm-token-value (car (last statement))) ":"))
                  (return-from python-mode-indentation (if (and (equal first "case") (equal head "match")) (+ level width) level)))
                (when (< level limit) (setf limit level))))))
        (cond ((equal (pm-token-value (car (last previous))) ":") (+ base width))
              ((member (pm-token-value (first previous)) '("return" "raise" "break" "continue" "pass") :test #'equal) (max 0 (- base width)))
              (t base))))))
(defun python-mode-levels (context)
  (let ((column (python-mode-indentation context)) (width (ictx-width context)))
    (when column (sort (remove-duplicates (cons column (loop for i from 0 to (+ column width) by width collect i))) #'<))))
(defun python-mode-definition-positions (source)
  (multiple-value-bind (statements pending) (pm-statements (pm-lex source))
    (let ((offsets (pm-offsets source)))
      (loop for statement in (append statements (when pending (list pending)))
            for head = (pm-token-value (first statement))
            when (or (member head '("def" "class") :test #'equal)
                     (and (equal head "async") (second statement) (equal (pm-token-value (second statement)) "def")))
              collect (aref offsets (pm-token-start (first statement)))))))
(defun python-mode-navigate (direction)
  (let* ((source (octets-string (buffer-octets 0 (buffer-size)) 0 (buffer-size)))
         (positions (python-mode-definition-positions source)) (here (point))
         (target (if (plusp direction) (find-if (lambda (p) (> p here)) positions)
                     (find-if (lambda (p) (< p here)) (reverse positions)))))
    (if target (goto-char target) (message "No further Python definition"))))
(defcommand python-next-definition () (python-mode-navigate 1))
(defcommand python-previous-definition () (python-mode-navigate -1))
(defun python-mode-file-p (filename)
  (and filename (member (string-downcase (or (pathname-type filename) "")) '("py" "pyw" "pyi" "synpy") :test #'equal)))
(defun python-mode-menu (buffer-name buttons)
  (if (if *menu-rendering* (python-mode-file-p *menu-filename*)
          (and (plusp (window-count))
               (call-in-window-of buffer-name (lambda () (python-mode-file-p (buffer-filename))))))
      (if *menu-full*
          (append (remove "QUIT" buttons :key #'first :test #'equal)
                  '(("#" "M-;") ("INDENT" menu-indent) ("DEF>" python-next-definition)
                    ("<DEF" python-previous-definition) ("QUIT" "C-x C-c")))
          (loop for button in buttons append
            (cond ((equal (first button) "?") (list button '("#" "M-;")))
                  ((equal (first button) "DELETE") (list button '("INDENT" menu-indent)))
                  ((equal (first button) "Select") (list '("MORE" more-menu) button))
                  ((equal (first button) "MORE") (if *menu-region* (list button) nil))
                  (t (list button)))))
      buttons))
(defun install-python-mode ()
  (define-language "Python" :extensions '(".py" ".pyw" ".pyi" ".synpy") :line-comment "#" :highlighter #'python-mode-highlight)
  (setf (gethash :python-smart *indent-styles*)
        (cons #'python-mode-indentation (lambda (text start) (declare (ignore text start)) nil)))
  (define-indentation "Python" :style :python-smart :width 4 :tabs nil :cycle t :levels #'python-mode-levels
                      :electric-keys ":" :electric-words '("elif" "else" "except" "finally" "case"))
  (install-mode-menu "python" #'python-mode-menu))
(register-editing-mode "python" #'install-python-mode)
